services:
    db:
      image: postgres
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: solutions
      ports:
        - "5432:5432"
      volumes:
        - ./docker:/docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5
    service:
      build: .
      environment:
        CUENCA_DB_HOST: db
      depends_on:
        db:
          condition: service_healthy

